### ISSUE TITLE
FreeRTOS mutex does not handle priority inversion

### ISSUE THREAD

**Issue by supergaute** [OpenAMP/libmetal#101]
Commit 10a0d5be removes the priority inheritance mechanism FreeRTOS is using with its mutexes.
Suggest to revert this commit.

**Comment by edmooring** [comment]
The reasoning behind the original change is that FreeRTOS mutexes can't be statically initialized, which conflicts with the bare metal and Linux implementations. This will take some additional code restructuring.

**Comment by supergaute** [comment]
Do you have any plans to do this restructuring in the near future?

**Comment by arnopo** [comment]
@ed, @bentheredonethat,
I'm agree  with @supergaute. we should take benefit of FreeRTOS mutex. 

I'm trying to understand why the mutex can not be statically initialized using FreeRTOS. I'm not familiar with freertos, so don't hesitate if i missed something.
In freertos there is the following function: xSemaphoreCreateBinaryStatic [1]

This function seems to allow the possibility to have a static semaphore allocation
Therefore we could not define the METAL_MUTEX_INIT. As this macro is not used by the open-amp library, this should not affect it.

My proposal would be to  revert the 10a0d5b, and having  a static 

```
typedef struct {	typedef struct {
        StaticSemaphore_t semaphore;
	SemaphoreHandle_t m;	
} metal_mutex_t;

#define METAL_MUTEX_DEFINE(m) metal_mutex_t m;

static inline void __metal_mutex_init(metal_mutex_t *mutex)	static inline void __metal_mutex_init(metal_mutex_t *mutex)
{	{
	metal_assert(mutex);		atomic_store(&mutex->v, 0);
	mutex->m = xSemaphoreCreateBinaryStatic(mutex->semaphore);	
	metal_assert(mutex->m != NULL);	
}	}

```
I'm not able to test it,  so could someone validate if the implementation could work using FreeRTOS? 
 
[1] https://www.freertos.org/xSemaphoreCreateBinaryStatic.html

**Comment by edmooring** [comment]
I'm inclined to revert the commit as well, and, since I can't find any evidence anybody is using METAL_MUTEX_INIT, deprecate it for this release, possibly with a compile time warning.

**Comment by bentheredonethat** [comment]
@edmooring  @arnopo any update on this? if not,  I can send PR to revert the commit

**Comment by arnopo** [comment]
I think you can send a PR to revert it, the current implementation seems not suitable for the freeRTOS. 
Just be sure that the METAL_MUTEX_INIT still exists. It is a macro, it will not possible to use the deprecated compilation attribute.

**Comment by arnopo** [comment]
Hi @bentheredonethat 
Do you plan to send a PR for the next release ?

**Comment by bentheredonethat** [comment]
Hi @arnopo  sorry won't have bandwidth on this one

**Comment by madscientist42** [comment]
Uhm...why is this still open?

**Comment by arnopo** [comment]
> Uhm...why is this still open?

You are right no reason to keep it open. If needed a new one can be opened

**Comment by madscientist42** [comment]
Heh.  Thank you.  If LOOKED like it might've been fixed but wasn't clear
and I'm about to start doing integration work and needed to know to tell a
client there might be gotchas.
