### ISSUE TITLE
Multiple shared libraries using libmetal

### ISSUE THREAD

**Issue by sjd-xlnx** [OpenAMP/libmetal#178]
Hopefully, more of a question than an issue.

I have 2 separate libraries both using libmetal to access h/w devices (different device each library). So, lets' say libA accesses deviceA and libB accesses deviceB. Now, in some cases, I'm just using libA / deviceA and in some cases I'm just using libB / deviceB. So far so good.

However, I now have an application that wants to use libA and libB, i.e. both deviceA and deviceB. The problem that I see here, is that since I'm using Linux shared libraries, the libmetal library is essentially common, i.e. used by both libA and libB, and as such it is sharing some static data structures.

In particular, I have a problem when I try to do "metal_finish()". For example: metal_finish() in libA works, but when I do metal_finish() in libB I get segmentation fault (because it was already "finished" by libA). I suspect there could be similar issues in other places.

How can work around this? Is there a correct way to handle this scenario?

Thanks.

**Comment by edmooring** [comment]
This seems to be a bug in the Linux libmetal implementation. The function returns void, so it can't return an error on multiple invocations, but it should not create a segfault.

**Comment by edmooring** [comment]
@sjd-xlnx Can you try https://github.com/OpenAMP/libmetal/pull/185 to see if this fixes your issue? It works in my limited testing.

**Comment by edmooring** [comment]
This entire problem could be avoided if libmetal took advantage of the ELF initialization and finalizations sections like most Linux (and other?) libraries. We could avoid the need for explicit initialization and finalization functions entirely.

**Comment by sjd-xlnx** [comment]
Hi, I looked at the proposed change, and it doesn't look right to me.

```
void metal_finish(void)
{
	/* if metal_init() failed, or metal_finish() is called twice, just return */
	if (_metal.common.initialized)
		return;
	metal_sys_finish();
	memset(&_metal, 0, sizeof(_metal));
}
```

Shouldn't it be something like this...
```
void metal_finish(void)
{
	/* if metal_init() failed, or metal_finish() is called twice, just return */
	if (!_metal.common.initialized)
		return;
	metal_sys_finish();
	memset(&_metal, 0, sizeof(_metal));
}
```

or ...
```
void metal_finish(void)
{
	/* if metal_init() failed, or metal_finish() is called twice, just return */
	if (_metal.common.initialized) {
		metal_sys_finish();
		memset(&_metal, 0, sizeof(_metal));
	}
	return;
}
```

**Comment by edmooring** [comment]
You're absolutely correct. The '!' is in my source tree but not in git. I must have messed something up in my edit.

**Comment by arnopo** [comment]
Should be Fixed by  https://github.com/OpenAMP/libmetal/pull/239, please reopen the issue if not the case.
