### ISSUE TITLE
lto1: fatal error: bytecode stream generated with LTO version 8.1 instead of the expected 4.0

### ISSUE THREAD

**Issue by wangyong5123** [OpenAMP/libmetal#182]
how to solve ?

**Comment by arnopo** [comment]
Hello @wangyong5123 

Please,  privide the context and traces. It difficult to understand the link between the libmetal library and your issue

**Comment by edmooring** [comment]
I think this is a problem with the installation of the Xilinx SDK. It looks like the wrong version of binutils is being used somewhere.

**Comment by arnopo** [comment]
@wangyong5123 
I close this issue, please reopen it or another one on need
