### ISSUE TITLE
RZG2L OpenAmp Renesas

### ISSUE THREAD

**Issue by PravinRaut123** [OpenAMP/libmetal#196]
I got the following errors while using OpenAmp in RZG2L SMARC Linux Image.

ERROR: libmetal-2018.10-r0 do_fetch: Fetcher failure: Unable to find revision 89276b531e0d982ede3e3c59a3832d0888b6d239 in branch master even from upstream
ERROR: libmetal-2018.10-r0 do_fetch: Fetcher failure for URL: 'git://github.com/OpenAMP/libmetal.git;protocol=https;branch=master'. Unable to fetch URL from any source.

How to do for this??

**Comment by arnopo** [comment]
Hello,
It seems that your problem is not related to a problem in libmetal but to your environment. proxy problem ?
I suggest you contact Renesas for support
I close the problem, please reopen it if my analysis is wrong.
