### ISSUE TITLE
FreeRTOS at higher tick rates bug

### ISSUE THREAD

**Issue by dtrussel** [OpenAMP/libmetal#69]
In `libmetal/lib/system/freertos/sleep.h`
```
static inline int __metal_sleep_usec(unsigned int usec)
{
	const TickType_t xDelay = usec / portTICK_PERIOD_MS;
	vTaskDelay(xDelay);
	return 0;
}
```

If the `configTICK_RATE_HZ` of is bigger than 1000 the `portTICK_PERIOD_MS` is 0 and you get division by zero (not recommended).
Better use `seconds * configTICK_RATE_HZ` to calculate how many ticks to sleep.

**Comment by wjliang** [comment]
> If the `configTICK_RATE_HZ` of is bigger than 1000 the `portTICK_PERIOD_MS` is 0 and you get division by zero (not recommended).

I just check the source code of Xilinx FreeRTOS porting, confirmed what you pointed out. Agree, should change to what you suggested.

Best Regards,
Wendy

**Comment by edmooring** [comment]
This is indeed an issue. We should probably be using pdMS_TO_TICKS() instead.

**Comment by edmooring** [comment]
See #143 for a possible fix.
